// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnrzsvtaeulxunxnbxtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucnpzdnRhZXVseHVueG5ieHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNTE2NjIsImV4cCI6MjA4MjYyNzY2Mn0.Rta8-ZcV0ta29HjF25bMOjJSp9jSGGv4l7dVdvDAalY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});